### ISSUE TITLE
Does not detect SemiAnnualEnterpriseChannel Versions since rename of the Channel

### ISSUE THREAD

**Issue by tobiasabele** [sanghocho89/Update365#1]
need to update line 62, to adress rename of Channels, tried with:

$deferred = [regex]::matches( $result, '<a href=\"(semi-annual-channel-(\d{4})|semi-annual-enterprise-channel#)(.*?)</a>')

seems to work

**Comment by scho89** [comment]
Thanks for your correction.
I modified line 62.

Have a nice day!
